spring.application.name=demo
logging.file.path=./logs
logging.file.name=./logs/application.log

# PostgreSQL configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=testapp
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=testapp
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.hbm2ddl.create_namespaces=true



